5a754dc3_7769045a_4eac82ab_4bafdcf0

[uuid here]

This file denotes the format of a plaintext message. The first and last lines must be (two different) uuids, formatted canonically, followed by a newline. The second and penultimate line must be empty (except for the required newline). There are no limitations whatsoever for other lines in the message. By calculating and publishing the checksums of the message, and creating a "signature" file, the contents have been written prior to when the signature is known. No cryptographic signing takes place.

[another uuid here]

b67f9d18_db7f532c_126e8341_772d30b0
